name: Keep Streamlit App Alive

on:
  schedule:
    # 한국 시간 기준 매일 아침 9시, 저녁 9시 (12시간마다)
    - cron: '0 0,12 * * *'
  workflow_dispatch: # 수동으로 실행하고 싶을 때 사용

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://gachon-hci-negotiation.streamlit.app/